"""add leads table

Revision ID: 25ae4fc65be4
Revises: a33f0d420da5
Create Date: 2026-09-19 15:23:30.116176

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '25ae4fc65be4'
down_revision: Union[str, Sequence[str], None] = 'a33f0d420da5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('leads',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('conversation_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('company', sa.String(length=200), nullable=True),
    sa.Column('team_size', sa.Integer(), nullable=True),
    sa.Column('need', sa.Text(), nullable=True),
    sa.Column('consent_prompt', sa.Text(), nullable=False),
    sa.Column('consent_reply', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id', 'organization_id'], ['conversations.id', 'conversations.organization_id'], name=op.f('fk_leads_conversation_id_conversations'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_leads_organization_id_organizations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_leads')),
    sa.UniqueConstraint('organization_id', 'conversation_id', name=op.f('uq_leads_organization_id'))
    )
    op.create_index('ix_leads_org_created', 'leads', ['organization_id', 'created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_leads_org_created', table_name='leads')
    op.drop_table('leads')
    # ### end Alembic commands ###
